#!/usr/bin/env python

from __future__ import print_function
import os
import kliko
from kliko.validate import validate

# validate and parse the kliko arguments
parameters = validate()

print("parameters:" + str(parameters))
os.chdir(kliko.work_path)
open('luigitest3 was here', 'a').close()
