#!/usr/bin/env python
"""
This is the simms kliko file. Is is ment to be called from
inside a kliko container. 
"""
import os
from kliko.validate import validate
import subprocess

binary = "/usr/local/bin/simms"

# changedir so simms will write results to kliko output folder
os.chdir("/output")

# validate and parse the kliko arguments
parameters = validate()

# format kliko arguments into simms arguments
cmd = [binary] + ["--{}={}".format(k, v) for k, v in parameters.items() if v]

# call the simms
subprocess.call(cmd)

